version: 2

jobs:
  build:
    docker:
      - image: nixos/nix:2.1.3
    steps:
      - checkout
      - run:
          name: System dependencies
          command: |
            apk update --no-progress && apk --no-progress add bash ca-certificates docker
      - run:
          name: Build image
          command: |
            nix-build server/docker.nix
      - setup_remote_docker:
            docker_layer_caching: true
      - run:
          name: Push image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker load < result
            docker tag novadiscovery/benchgraph:latest benchgraph/benchgraph:$CIRCLE_BRANCH
            docker push benchgraph/benchgraph:$CIRCLE_BRANCH
